Sandbox/exerciseweek3/exerciseweek3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('netflix.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sandbox/exerciseweek3/netflix/urls.py
from django.urls import path
from . import views

app_name = 'netflix'

urlpatterns = [
    path('', views.accounts, name="accounts"),
    path('videos', views.videos, name="videos"),
    path('genres/', views.genres, name="genres"),
]

Sandbox/exerciseweek3/netflix/models.py
from django.db import models


class Account(models.Model):
    name = models.CharField(max_length=150)
    image = models.ImageField()

    def __str__(self):
        return self.name


class Video(models.Model):
    title = models.CharField(max_length=256)
    duration = models.IntegerField()
    description = models.TextField()
    picture = models.ImageField()
    genre = models.ManyToManyField('Genre')

    def __str__(self):
        return f'Video: {self.title}'


class Genre(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f'Genre: {self.name}'

Sandbox/exerciseweek3/netflix/views.py
from django.shortcuts import render
from .models import Genre, Video, Account


def accounts(request):
    accounts = Account.objects.all()
    return render(request, 'accounts.html', {'accounts': accounts})


def videos(request):
    videos = Video.objects.all()
    return render(request, 'videos.html', {'videos': videos})


def genres(request):
    genres = Genre.objects.all()
    return render(request, 'genres.html', {'genres': genres})

Sandbox/exerciseweek3/netflix/templates/accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Account</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'netflix/accounts.css' %}"/>
</head>
<body class="custom-background">
    <h1 class="logo">Crappy Netflix</h1>

    <div class="custom-card-container">
        {% for account in accounts %}
            <a href="{% url 'netflix:videos' %}">
                <div class="column custom-card">
                    <div class="ui fluid card">
                      <div class="image">
                        <img src="{{ account.image.url }}">
                      </div>
                      <div class="content">
                        <h2 class="account-name">{{ account.name }}</h2>
                      </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous"></script>
</body>
</html>

Sandbox/exerciseweek3/netflix/templates/genres.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Genres</title>
</head>
<body>
    Genres

    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous"></script>
</body>
</html>

Sandbox/exerciseweek3/netflix/templates/videos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Videos</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'netflix/videos.css' %}"/>
</head>
<body class="custom-background">
    <h1 class="logo">Crappy Netflix</h1>

    <div class="custom-card-container">
        {% for video in videos %}
            <a href="#">
                <div class="column custom-card">
                    <div class="ui fluid card">
                      <div class="image">
                        <img src="{{ video.picture.url }}">
                      </div>
                      <div class="content">
                        <h3 class="video-title">{{ video.title }}</h3>
                      </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous"></script>
</body>
</html>